#!/bin/sh
set -e

# Run as current user
VM_OPTIONS=$(< /kool/kool.vmoptions grep -Ev "^(#.*|.*=$)")
if [ -e "${CLASSPATH}" ]; then
  if [ -f pom.xml ]; then
    if [ -e "$(command -v mvn)" ]; then
      echo "This image not contains Maven"
      exit 1;
    fi

    CLASSPATH=$(mvn -q exec:exec -Dexec.executable=echo -Dexec.args="%classpath")
  fi

  if [ -f build.gradle ]; then
    if [ -n "$(command -v gradle)" ]; then
      echo "This image not contains Gradle"
      exit 1;
    fi

    if ! [ -f kool.gradle ]; then
      cat > kool.gradle <<EOF
task classPath {
    println "\${sourceSets.main.runtimeClasspath.collect().join(':')}"
}

EOF
      printf "\napply from: 'kool.gradle'\n" >> build.gradle
    fi

    CLASSPATH=$(gradle -q classPath)
  fi
fi

RUN="java ${VM_OPTIONS} ${JAVA_OPTIONS} -cp ${CLASSPATH} ${MAIN_CLASS}"

# Run entrypoint if provided
if [ -n "${ENTRYPOINT}" ] && [ -f "${ENTRYPOINT}" ]; then
    bash "${ENTRYPOINT}"
fi

if [ "$1" = "bash" ] || [ "$1" = "java" ] || [ "$1" = "jshell" ] || [ "$1" = "mvn" ]  || [ "$1" = "gradle" ]; then
  exec "${@}"
else
  exec "${RUN}" "${@}"
fi
