#!/bin/sh
set -e

# Run as current user
CURRENT_USER=${ASUSER:-${UID:-0}}
VM_OPTIONS=$(< /kool/kool.vmoptions grep -Ev "^#.*")
RUN="java ${VM_OPTIONS} ${JAVA_OPTIONS} -jar ${JAR_FILE}"

if [ -n "${CURRENT_USER}" ] && [ "${CURRENT_USER}" != "0" ]; then
    usermod -u "${CURRENT_USER}" kool
fi

# Run entrypoint if provided
if [ -n "${ENTRYPOINT}" ] && [ -f "${ENTRYPOINT}" ]; then
    bash "${ENTRYPOINT}"
fi

if [ "$1" = "bash" ] || [ "$1" = "java" ] || [ "$1" = "jshell" ]; then
  if [ -n "${CURRENT_USER}" ] && [ "${CURRENT_USER}" != "0" ]; then
    exec su-exec kool "${@}"
  else
    exec "${@}"
  fi
else
  if [ -n "${CURRENT_USER}" ] && [ "${CURRENT_USER}" != "0" ]; then
    exec su-exec kool "${RUN}" "${@}"
  else
    exec "${RUN}" "${@}"
  fi
fi
